CREATE DATABASE IF NOT EXISTS DB_CODEHUCK;
CREATE USER IF NOT EXISTS 'saged'@'localhost' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON DB_CODEHUCK.* TO 'saged'@'localhost';
GRANT SELECT ON performance_schema.* TO 'saged'@'localhost';
FLUSH PRIVILEGES;